import React from "react";
import { FaExternalLinkAlt } from "react-icons/fa";
import "./About.css";

function AboutPage() {
  return (
    <div className="resume-page">
      <header className="resume-header">
        <h1>Resume</h1>
      </header>
      <hr />

      <section className="resume-section">
        <h2 className="section-title">Work Experience</h2>
        <div className="section-content">
          <div className="work-item">
            <div className="work-title">
              <strong>
                Operations Associate at
                <a
                  href="https://www.vedantu.com"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Vedantu Innovations Pvt. Ltd. <FaExternalLinkAlt />
                </a>
              </strong>
              <p>Duration: 07-2021 to 08-2023</p>
            </div>
            <div className="work-details">
              <p className="responsibilities-title">Responsibilities</p>
              <ul className="responsibilities">
                <li>
                  Created new Course, Batch and Sessions based on requirements
                </li>
                <li>
                  Launched a new Long-term course on a weekly basis, and shared
                  mail notification to the students & teachers.
                </li>
                <li>
                  Actively responded to all the inquiries received from
                  different teams, and resolved them on time.
                </li>
                <li>
                  Collaborated with cross-functional teams to develop innovative
                  solutions for the complex operational challenges.
                </li>
                <li>
                  Took ownership & worked individually on creating Micro-Courses
                  and uploaded it within the given timeline.
                </li>
                <li>
                  Increased customer satisfaction rates through diligent
                  monitoring of service quality and addressing client concerns
                  promptly.
                </li>
                <li>
                  Cultivated strong relationships with key stakeholders
                  throughout the organization.
                </li>
                <li>
                  Managed project timelines, ensuring timely completion of tasks
                  and meeting overall objectives.
                </li>
              </ul>
            </div>
          </div>

          <div className="work-item">
            <div className="work-title">
              <strong>
                Data Analyst Intern at
                <a
                  href="https://www.gfactors.co.in"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Gfactors <FaExternalLinkAlt />
                </a>
              </strong>
              <p>Duration: 02-2020 to 08-2020</p>
            </div>
            <div className="work-details">
              <p className="responsibilities-title">Responsibilities</p>
              <ul className="responsibilities">
                <li>
                  By understanding the need for Annotations & sentiment tagging,
                  enhanced the quality of results generated by AI- ML models.
                </li>
                <li>
                  Analyzed the user's intention and identified whether it
                  relates to an opinion, news, marketing, complaint, suggestion,
                  appreciation or query.
                </li>
                <li>
                  Annotated the training data by human experts to prepare the
                  raw data, which is consumed by machines.
                </li>
                <li>
                  Have served Global brands across industries like Consumer
                  Electronics, Banking, Telecom, Healthcare, Luxury & Lifestyle
                  Brands, Automobile, Information Technology, Retail etc.
                </li>
                <li>
                  Decoded live lines of customer feedback for the clients to
                  accelerate their AI and Machine Learning models.
                </li>
                <li>
                  Supported project management efforts by tracking deadlines and
                  providing timely updates on progress.
                </li>
                <li>
                  Demonstrated strong organizational and time management skills
                  while managing multiple projects.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <hr />

      <section className="resume-section">
        <h2 className="section-title">Education</h2>
        <div className="section-content">
          <div className="education-item">
            <p className="education-degree">
              <strong>MSc in Information Technology</strong>
              <p>Manipal Institute of Technology (MAHE)</p>
            </p>
            <p>06-2018 to 05-2020 | Manipal, India</p>
          </div>
          <div className="education-item">
            <p className="education-degree">
              <strong>Bachelor of Computer Applications (BCA)</strong>
              <p>Mahathma Gandhi Memorial College</p>
            </p>
            <p>06-2015 to 05-2018 | Udupi, India</p>
          </div>
        </div>
      </section>
      <hr />
    </div>
  );
}

export default AboutPage;
